version: '3.1'
name: mykytenko-mysql-redis
services:

  mysql:
    image: mysql:8.0
    container_name: mysqlContainer
    restart: unless-stopped
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./resources/dump-hibernate-final.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql:/var/lib/mysql

  redis:
    image: redis/redis-stack:latest
    container_name: redisContainer
    ports:
      - "6379:6379"
      - "8001:8001"
    depends_on: [mysql]

  java:
    build: .
    container_name: javaContainer
    depends_on: [redis]

volumes:
  mysql:
